---
http_interactions:
- request:
    method: get
    uri: https://maps.googleapis.com/maps/api/geocode/json?sensor=false&address=Crazy+Unknown+Non-Existent+Place&key=
    body:
      encoding: US-ASCII
      string: ''
    headers:
      accept:
      - ! '*/*'
      user-agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      content-type:
      - application/json; charset=UTF-8
      date:
      - Fri, 24 Jun 2016 18:37:14 GMT
      expires:
      - Sat, 25 Jun 2016 18:37:14 GMT
      cache-control:
      - public, max-age=86400
      access-control-allow-origin:
      - ! '*'
      server:
      - mafe
      x-xss-protection:
      - 1; mode=block
      x-frame-options:
      - SAMEORIGIN
      alternate-protocol:
      - 443:quic
      alt-svc:
      - quic=":443"; ma=2592000; v="34,33,32,31,30,29,28,27,26,25"
      accept-ranges:
      - none
      vary:
      - Accept-Language,Accept-Encoding
      transfer-encoding:
      - chunked
    body:
      encoding: US-ASCII
      string: ! "{\n   \"results\" : [],\n   \"status\" : \"ZERO_RESULTS\"\n}\n"
    http_version: '1.1'
  recorded_at: Fri, 24 Jun 2016 18:37:14 GMT
recorded_with: VCR 2.6.0
