shared: &shared
  adapter: mysql2
  database: <%= ENV["MYSQL_DATABASE"] || 'federalregister-api-core'%>
  username: <%= ENV["MYSQL_USERNAME"] || 'root' %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  port: <%= ENV["MYSQL_PORT"] || 3306 %>
  host: '<%= ENV["MYSQL_ADDR"] || '127.0.0.1' %>'
  reconnect: true
  encoding: utf8

development:
  <<: *shared

test:
  <<: *shared
  database: <%= ENV["MYSQL_DATABASE"] %>_test

staging:
  <<: *shared

production:
  <<: *shared
