development:
  host: 127.0.0.1
  port: 6379
  db: 0
test:
  host: 127.0.0.1
  port: 6379
  db: 0
staging:
  host: redis.fr2.ec2.internal
  port: 6379
  db: 0
officialness_staging:
  host: redis.fr2.ec2.internal
  port: 6379
  db: 0
production:
  host: redis.fr2.ec2.internal
  port: 6379
  db: 0
