api_keys:
  google_maps_geocode: <%= ENV['GOOGLE_MAPS_GEOCODE'] %>
  yahoo_placemaker: <%= ENV['YAHOO_PLACEMAKER'] %>
  flickr: <%= ENV['FLICKR'] %>
  flickr_secret: <%= ENV['FLICKR_SECRET'] %>
  honeybadger: <%= ENV['HONEYBADGER'] %>

aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

email_salt: <%= ENV['EMAIL_SALT'] %>

data_dot_gov:
  api_key: <%= ENV['DATA_DOT_GOV_API_KEY'] %>

redis:
  host: <%= ENV['REDIS_PORT_6379_TCP_ADDR'] || '127.0.0.1' %>
  port: <%= ENV['REDIS_PORT_6379_TCP_PORT'] || 6379 %>
  db: <%= ENV['REDIS_DB'] || 0 %>

sendgrid:
  username: <%= ENV['SENDGRID_USERNAME'] %>
  password: <%= ENV['SENDGRID_PASSWORD'] %>

session_key: <%= ENV['RAILS_SESSION_KEY'] %>
