api_keys:
  google_maps_geocode: <%= ENV['GOOGLE_MAPS_GEOCODE'] %>
  yahoo_placemaker: <%= ENV['YAHOO_PLACEMAKER'] %>
  flickr: <%= ENV['FLICKR'] %>
  flickr_secret: <%= ENV['FLICKR_SECRET'] %>
  recaptcha_public: <%= ENV['RECAPTCHA_PUBLIC'] %>
  recaptcha_private: <%= ENV['RECAPTCHA_PRIVATE'] %>
  honeybadger: <%= ENV['HONEYBADGER'] %>

aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

email_salt: <%= ENV['EMAIL_SALT'] %>

data_dot_gov:
  api_key: <%= ENV['DATA_DOT_GOV_API_KEY'] %>

sendgrid:
  username: <%= ENV['SENDGRID_USERNAME'] %>
  password: <%= ENV['SENDGRID_PASSWORD'] %>

session_key: <%= ENV['RAILS_SESSION_KEY'] %>
