development:
  morphology: stem_en
  index_exact_words: 1
test:
  morphology: stem_en
  index_exact_words: 1
production:
  morphology: stem_en
  index_exact_words: 1
  searchd_log_file: /var/www/apps/fr2/shared/log/searchd.log
  query_log_file: /var/www/apps/fr2/shared/log/searchd.query.log
  pid_file: /var/www/apps/govpulse/fr2/tmp/searchd.pid
  searchd_file_path: /var/www/apps/fr2/shared/db/sphinx/production
