# Our chef setup no longer overwrites this file...
development:
  version: '2.0.5'
  morphology: stem_en
  index_exact_words: 1
  mem_limit: 528M
  listen: 127.0.0.1:9339
  port: 9339
  compat_sphinxql_magics: 0
  max_matches: 10000
test:
  version: '2.0.5'
  morphology: stem_en
  index_exact_words: 1
  max_matches: 10000
  listen: 127.0.0.1:9340
  port: 9340
  compat_sphinxql_magics: 0
  max_matches: 10000
  sql_range_step: 10000000
staging:
  morphology: stem_en
  index_exact_words: 1
  address: sphinx.fr2.ec2.internal
  port: 3312
  mem_limit: 528M
  version: '2.0.6'
  searchd_log_file: /var/www/apps/fr2/shared/log/searchd.log
  query_log_file: /var/www/apps/fr2/shared/log/searchd.query.log
  pid_file: /var/www/apps/fr2/shared/tmp/searchd.pid
  searchd_file_path: /var/www/apps/fr2/shared/db/sphinx/production
  compat_sphinxql_magics: 0
  max_matches: 10000
production:
  morphology: stem_en
  index_exact_words: 1
  address: sphinx.fr2.ec2.internal
  port: 3312
  mem_limit: 528M
  version: '2.0.1'
  searchd_log_file: /var/www/apps/fr2/shared/log/searchd.log
  query_log_file: /var/www/apps/fr2/shared/log/searchd.query.log
  pid_file: /var/www/apps/fr2/shared/tmp/searchd.pid
  searchd_file_path: /var/www/apps/fr2/shared/db/sphinx/production
  compat_sphinxql_magics: 0
  max_matches: 10000
